### ISSUE TITLE
你好，请教一下vimrc设置中的一行内容。

### ISSUE THREAD

**Issue by myme5261314** [asins/vim#1]
本来我用你的配置文件用得很好的。
但是现在突然出现一个问题，我是64位Win7，用得gvim.exe是从你这里下的64位的exe。
现在突然出现一个问题，64位的exe打不开，32位的vim官网的exe能打开。
最后我排查了vimrc的内容，发现有一行:Bundle 'yangzetian/RST-Tables'。
将这一行内容注释之后就可以启动64位的exe，取消注释就打不开了。32位的exe没有影响，都能打开。所以我在想是不是你编译的64位的exe有点什么问题？如果你知道问题在哪里，麻烦告诉我一下。mailto:myme5261314@gmail.com

**Comment by asins** [comment]
Sorry，rst插件只是预使用性的，目前已经在我的vimrc中删除了，你也删除吧！近期会更新一次
Asins Sent from M9

-------- 原始邮件 --------
发件人：myme5261314 notifications@github.com
时间：2013-1-20 14:50
收件人：asins/vim vim@noreply.github.com
主题：[vim] 你好，请教一下vimrc设置中的一行内容。 (#1)

本来我用你的配置文件用得很好的。
但是现在突然出现一个问题，我是64位Win7，用得gvim.exe是从你这里下的64位的exe。
现在突然出现一个问题，64位的exe打不开，32位的vim官网的exe能打开。
最后我排查了vimrc的内容，发现有一行:Bundle 'yangzetian/RST-Tables'。
将这一行内容注释之后就可以启动64位的exe，取消注释就打不开了。32位的exe没有影响，都能打开。所以我在想是不是你编译的64位的exe有点什么问题？如果你知道问题在哪里，麻烦告诉我一下。mailto:myme5261314@gmail.com

---

Reply to this email directly or view it on GitHub:
https://github.com/asins/vim/issues/1
